export AUTH0_DOMAIN="dev-5lzfargwj11n1quu.us.auth0.com"
export API_AUDIENCE="casting"
export ALGORITHMS="RS256"
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/casting"
export assistant_token="ADD_YOUR_ASSISTANT_TOKEN_HERE"
export director_token="ADD_YOUR_DIRECTOR_TOKEN_HERE"
export producer_token="ADD_YOUR_PRODUCER_TOKEN_HERE"
